services:
  - type: web
    name: tokenq-backend
    env: node
    plan: free
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: SUPER_ADMIN_EMAIL
        sync: false
      - key: SUPER_ADMIN_PASSWORD
        sync: false
      - key: SUPER_ADMIN_NAME
        sync: false
      - key: DEFAULT_ORG_NAME
        sync: false
      - key: DEFAULT_ORG_TYPE
        sync: false
      - key: DEFAULT_OWNER_NAME
        sync: false
      - key: DEFAULT_ORG_EMAIL
        sync: false
      - key: DEFAULT_ORG_PHONE
        sync: false
      - key: DEFAULT_ORG_PASSWORD
        sync: false
