services:
  - type: web
    name: tokenq-backend
    env: node
    plan: free
    buildCommand: npm run build
    startCommand: npm start
    envVars:
      - key: CLIENT_URL
        sync: false
      - key: COOKIE_DOMAIN
        sync: false
      - key: COOKIE_SECURE
        sync: false
      - key: MONGODB_URI
        sync: false
      - key: JWT_SECRET
        sync: false
      - key: JWT_EXPIRES_IN
        sync: false
      - key: CORS_ORIGIN
        sync: false
      - key: SUPER_ADMIN_EMAIL
        sync: false
      - key: SUPER_ADMIN_PASSWORD
        sync: false
      - key: SUPER_ADMIN_NAME
        sync: false
      - key: DEFAULT_ORG_NAME
        sync: false
      - key: DEFAULT_ORG_TYPE
        sync: false
      - key: DEFAULT_OWNER_NAME
        sync: false
      - key: DEFAULT_ORG_EMAIL
        sync: false
      - key: DEFAULT_ORG_PHONE
        sync: false
      - key: DEFAULT_ORG_PASSWORD
        sync: false
      - key: SMTP_HOST
        sync: false
      - key: SMTP_PORT
        sync: false
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
      - key: SMTP_FROM
        sync: false
